FROM python

WORKDIR /app

COPY . .

# Add bash
RUN pip install flask
RUN pip install xgboost
RUN pip install sklearn
RUN pip install flask_cors
RUN pip install pandas
RUN pip install numpy
RUN pip install boto3
 

EXPOSE 5000

CMD ["python", "Xgboost.py"]